import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { LanguageContext, type Language } from './language-context';

const translations: Record<string, string> = {
    'Organizing your life :D': 'Organizando tua vida :D', 'Boards': 'Quadros', 'What needs to happen?': 'O que precisa ser feito?',
    'Workspace navigation': 'Navegação do espaço de trabalho', 'Create board': 'Criar quadro', 'BOARDS': 'QUADROS',
    'Accounts': 'Contas', 'Profile & settings': 'Perfil e configurações', 'Open profile': 'Abrir perfil',
    'Administrator': 'Administrador', 'Member': 'Membro', 'Expand sidebar': 'Expandir barra lateral', 'Collapse sidebar': 'Recolher barra lateral',
    'Search tickets': 'Buscar tarefas', 'Search cards...': 'Buscar cartões...', 'Sign out': 'Sair', 'ticket': 'tarefa', 'tickets': 'tarefas', 'Refresh board': 'Atualizar quadro',
    'Your workspace, ready.': 'Seu espaço de trabalho está pronto.', 'Create a board': 'Criar um quadro', 'Filters': 'Filtros', 'Tags': 'Etiquetas',
    'Assignee': 'Responsável', 'Filter by assignee': 'Filtrar por responsável', 'All assignees': 'Todos os responsáveis', 'Unassigned': 'Sem responsável',
    'Priority': 'Prioridade', 'Filter by priority': 'Filtrar por prioridade', 'All priorities': 'Todas as prioridades', 'Urgent': 'Urgente', 'High': 'Alta', 'Normal': 'Normal', 'Low': 'Baixa',
    'Clear filters': 'Limpar filtros', 'Done': 'Concluído', 'Archive': 'Arquivar', 'Archive list': 'Arquivo', 'New ticket': 'Nova tarefa', 'Title': 'Título', 'Column': 'Coluna', 'Create ticket': 'Criar tarefa',
    'Sign in': 'Entrar', 'Email': 'E-mail', 'Password': 'Senha', 'Unable to sign in.': 'Não foi possível entrar.', 'Dark theme': 'Tema escuro', 'Light theme': 'Tema claro',
    'Ticket': 'Tarefa', 'Ticket title': 'Título da tarefa', 'Edit title': 'Editar título', 'Preview title': 'Visualizar título', 'Description': 'Descrição', 'Preview description': 'Visualizar descrição', 'Edit description': 'Editar descrição', 'Add a description': 'Adicione uma descrição', 'No description': 'Sem descrição',
    'Subtasks': 'Subtarefas', 'Complete': 'Concluir', 'Subtask title': 'Título da subtarefa', 'Remove subtask': 'Remover subtarefa', 'Move subtask': 'Mover subtarefa', 'New subtask': 'Nova subtarefa', 'Add a subtask': 'Adicionar uma subtarefa', 'Add subtask': 'Adicionar subtarefa',
    'Images': 'Imagens', 'Add image': 'Adicionar imagem', 'View attached image': 'Ver imagem anexada', 'Ticket attachment': 'Anexo da tarefa', 'Remove image': 'Remover imagem',
    'Comments': 'Comentários', 'Former member': 'Ex-membro', 'Delete comment': 'Excluir comentário', 'New comment': 'Novo comentário', 'Write a comment': 'Escreva um comentário', 'Post comment': 'Publicar comentário', 'Press Ctrl + Enter to post': 'Pressione Ctrl + Enter para publicar', 'Activity history': 'Histórico de atividade', 'created this ticket': 'criou esta tarefa', 'added a comment': 'adicionou um comentário', 'deleted a comment': 'excluiu um comentário', 'added an attachment': 'adicionou um anexo', 'removed an attachment': 'removeu um anexo', 'changed': 'alterou', 'empty': 'vazio',
    'Status': 'Status', 'Due date': 'Data de entrega', 'Delete ticket': 'Excluir tarefa', 'Restore': 'Restaurar', 'Save changes': 'Salvar alterações', 'Delete ticket?': 'Excluir tarefa?', 'Discard changes?': 'Descartar alterações?',
    'Cancel': 'Cancelar', 'Delete permanently': 'Excluir permanentemente', 'Discard': 'Descartar', 'Attached image': 'Imagem anexada', 'The ticket, comments and images will be permanently deleted.': 'A tarefa, os comentários e as imagens serão excluídos permanentemente.', 'Your unsaved changes will be lost.': 'Suas alterações não salvas serão perdidas.',
    'Move ticket': 'Mover tarefa', 'Add ticket': 'Adicionar tarefa', 'No tickets': 'Nenhuma tarefa', 'Open ticket': 'Abrir tarefa',
    'Archive ticket': 'Arquivar tarefa', 'Restore ticket': 'Restaurar tarefa', 'Archived': 'Arquivados', 'Search archive': 'Buscar no arquivo', 'No completed tickets': 'Nenhuma tarefa concluída', 'No archived tickets': 'Nenhuma tarefa arquivada',
    'Board settings': 'Configurações do quadro', 'Name': 'Nome', 'Members': 'Membros', 'Columns': 'Colunas', 'Completed column': 'Coluna de concluídos', 'Add column': 'Adicionar coluna', 'New column': 'Nova coluna', 'Delete board': 'Excluir quadro', 'Delete board?': 'Excluir quadro?',
    'All tickets, comments and images in this board will be permanently deleted.': 'Todas as tarefas, comentários e imagens deste quadro serão excluídos permanentemente.', 'Save board': 'Salvar quadro', 'Move up': 'Mover para cima', 'Move down': 'Mover para baixo', 'Remove column': 'Remover coluna',
    'Profile': 'Perfil', 'Security': 'Segurança', 'MCP': 'MCP', 'Change photo': 'Alterar foto', 'Appearance': 'Aparência', 'Light': 'Claro', 'Dark': 'Escuro', 'Custom settings': 'Configurações personalizadas', 'Save profile': 'Salvar perfil',
    'Current password': 'Senha atual', 'New password': 'Nova senha', '14 characters minimum': 'Mínimo de 14 caracteres', 'Changing your password ends all sessions and revokes all MCP tokens.': 'A alteração da senha encerra todas as sessões e revoga todos os tokens MCP.', 'Change password': 'Alterar senha',
    'MCP endpoint': 'Endpoint MCP', 'Token name': 'Nome do token', 'Create token': 'Criar token', 'Copy this token now. It will not be shown again. Send it as Authorization: Bearer <token>.': 'Copie este token agora. Ele não será exibido novamente. Envie-o como Authorization: Bearer <token>.', 'New token': 'Novo token', 'Copied': 'Copiado', 'Copy token': 'Copiar token', 'Assigned boards': 'Quadros atribuídos', 'No boards selected': 'Nenhum quadro selecionado', 'Clear boards': 'Limpar quadros', 'assigned': 'atribuídos', 'No board access': 'Sem acesso a quadros', 'Save boards': 'Salvar quadros', 'Revoke token': 'Revogar token',
    'Account management': 'Gerenciar contas', 'Disabled': 'Desativada', 'Admin': 'Administrador', 'Manage account': 'Gerenciar conta', 'New account': 'Nova conta', 'Initial password': 'Senha inicial', 'System administrator': 'Administrador do sistema', 'Boards this user can access': 'Quadros que este usuário pode acessar', 'Disabled account': 'Conta desativada', 'Reset password': 'Redefinir senha', 'Leave blank to keep the current password': 'Deixe vazio para manter a senha atual', 'Save account': 'Salvar conta', 'Create account': 'Criar conta',
    'Bug': 'Erro', 'Feature': 'Recurso', 'Design': 'Design', 'Docs': 'Documentação', 'Refactor': 'Refatoração', 'Test': 'Teste', 'Chore': 'Manutenção', 'Research': 'Pesquisa',
    'Language': 'Idioma', 'English': 'English', 'Português (Brasil)': 'Português (Brasil)', 'Choose language': 'Escolher idioma', 'Photo zoom': 'Zoom da foto',
    'Backup': 'Backup', 'Connect a Dropbox app to store automatic database backups. Backups run 10 minutes after changes stop. If changes continue, a backup runs after 1 hour without a saved backup.': 'Conecte um aplicativo Dropbox para armazenar backups automáticos do banco de dados. O backup é feito após 10 minutos sem alterações. Se as alterações continuarem, um backup será feito após 1 hora sem salvar.', 'Dropbox app key': 'Chave do aplicativo Dropbox', 'Dropbox access token': 'Token de acesso do Dropbox', 'Enter a new token to replace the saved token': 'Informe um novo token para substituir o token salvo', 'Dropbox connected': 'Dropbox conectado', 'Dropbox not connected': 'Dropbox não conectado', 'Last backup': 'Último backup', 'Last backup error': 'Erro no último backup', 'Disconnect': 'Desconectar', 'Back up now': 'Fazer backup agora', 'Save Dropbox settings': 'Salvar configurações do Dropbox', 'Connect Dropbox': 'Conectar ao Dropbox', 'Dropbox connected successfully.': 'Dropbox conectado com sucesso.', 'Dropbox disconnected.': 'Dropbox desconectado.', 'Backup completed.': 'Backup concluído.', 'Dropbox connection failed.': 'Falha ao conectar ao Dropbox.', 'Dropbox disconnection failed.': 'Falha ao desconectar o Dropbox.', 'Backup failed. Check the Dropbox connection and try again.': 'Falha no backup. Verifique a conexão com o Dropbox e tente novamente.',
};

const spanishTranslations: Record<string, string> = {
    'Organizing your life :D': 'Organiza tu vida :D', 'Boards': 'Tableros', 'What needs to happen?': '¿Qué hay que hacer?',
    'Workspace navigation': 'Navegación del espacio de trabajo', 'Create board': 'Crear tablero', 'BOARDS': 'TABLEROS',
    'Accounts': 'Cuentas', 'Profile & settings': 'Perfil y configuración', 'Open profile': 'Abrir perfil',
    'Administrator': 'Administrador', 'Member': 'Miembro', 'Expand sidebar': 'Expandir barra lateral', 'Collapse sidebar': 'Contraer barra lateral',
    'Search tickets': 'Buscar tareas', 'Search cards...': 'Buscar tarjetas...', 'Sign out': 'Cerrar sesión', 'ticket': 'tarea', 'tickets': 'tareas', 'Refresh board': 'Actualizar tablero',
    'Your workspace, ready.': 'Tu espacio de trabajo está listo.', 'Create a board': 'Crear un tablero', 'Filters': 'Filtros', 'Tags': 'Etiquetas',
    'Assignee': 'Responsable', 'Filter by assignee': 'Filtrar por responsable', 'All assignees': 'Todos los responsables', 'Unassigned': 'Sin asignar',
    'Priority': 'Prioridad', 'Filter by priority': 'Filtrar por prioridad', 'All priorities': 'Todas las prioridades', 'Urgent': 'Urgente', 'High': 'Alta', 'Normal': 'Normal', 'Low': 'Baja',
    'Clear filters': 'Borrar filtros', 'Done': 'Listo', 'Archive': 'Archivar', 'Archive list': 'Archivo', 'New ticket': 'Nueva tarea', 'Title': 'Título', 'Column': 'Columna', 'Create ticket': 'Crear tarea',
    'Sign in': 'Iniciar sesión', 'Email': 'Correo electrónico', 'Password': 'Contraseña', 'Unable to sign in.': 'No se pudo iniciar sesión.', 'Dark theme': 'Tema oscuro', 'Light theme': 'Tema claro',
    'Ticket': 'Tarea', 'Ticket title': 'Título de la tarea', 'Edit title': 'Editar título', 'Preview title': 'Vista previa del título', 'Description': 'Descripción', 'Preview description': 'Vista previa de la descripción', 'Edit description': 'Editar descripción', 'Add a description': 'Agrega una descripción', 'No description': 'Sin descripción',
    'Subtasks': 'Subtareas', 'Complete': 'Completar', 'Subtask title': 'Título de la subtarea', 'Remove subtask': 'Eliminar subtarea', 'Move subtask': 'Mover subtarea', 'New subtask': 'Nueva subtarea', 'Add a subtask': 'Agregar una subtarea', 'Add subtask': 'Agregar subtarea',
    'Images': 'Imágenes', 'Add image': 'Agregar imagen', 'View attached image': 'Ver imagen adjunta', 'Ticket attachment': 'Archivo adjunto de la tarea', 'Remove image': 'Eliminar imagen',
    'Comments': 'Comentarios', 'Former member': 'Exmiembro', 'Delete comment': 'Eliminar comentario', 'New comment': 'Nuevo comentario', 'Write a comment': 'Escribe un comentario', 'Post comment': 'Publicar comentario', 'Press Ctrl + Enter to post': 'Presiona Ctrl + Enter para publicar', 'Activity history': 'Historial de actividad', 'created this ticket': 'creó esta tarea', 'added a comment': 'agregó un comentario', 'deleted a comment': 'eliminó un comentario', 'added an attachment': 'agregó un archivo adjunto', 'removed an attachment': 'eliminó un archivo adjunto', 'changed': 'cambió', 'empty': 'vacío',
    'Status': 'Estado', 'Due date': 'Fecha de entrega', 'Delete ticket': 'Eliminar tarea', 'Restore': 'Restaurar', 'Save changes': 'Guardar cambios', 'Delete ticket?': '¿Eliminar tarea?', 'Discard changes?': '¿Descartar cambios?',
    'Cancel': 'Cancelar', 'Delete permanently': 'Eliminar permanentemente', 'Discard': 'Descartar', 'Attached image': 'Imagen adjunta', 'The ticket, comments and images will be permanently deleted.': 'La tarea, los comentarios y las imágenes se eliminarán permanentemente.', 'Your unsaved changes will be lost.': 'Se perderán los cambios sin guardar.',
    'Move ticket': 'Mover tarea', 'Add ticket': 'Agregar tarea', 'No tickets': 'No hay tareas', 'Open ticket': 'Abrir tarea',
    'Archive ticket': 'Archivar tarea', 'Restore ticket': 'Restaurar tarea', 'Archived': 'Archivadas', 'Search archive': 'Buscar en el archivo', 'No completed tickets': 'No hay tareas completadas', 'No archived tickets': 'No hay tareas archivadas',
    'Board settings': 'Configuración del tablero', 'Name': 'Nombre', 'Members': 'Miembros', 'Columns': 'Columnas', 'Completed column': 'Columna de tareas completadas', 'Add column': 'Agregar columna', 'New column': 'Nueva columna', 'Delete board': 'Eliminar tablero', 'Delete board?': '¿Eliminar tablero?',
    'All tickets, comments and images in this board will be permanently deleted.': 'Todas las tareas, los comentarios y las imágenes de este tablero se eliminarán permanentemente.', 'Save board': 'Guardar tablero', 'Move up': 'Mover hacia arriba', 'Move down': 'Mover hacia abajo', 'Remove column': 'Eliminar columna',
    'Profile': 'Perfil', 'Security': 'Seguridad', 'MCP': 'MCP', 'Change photo': 'Cambiar foto', 'Appearance': 'Apariencia', 'Light': 'Claro', 'Dark': 'Oscuro', 'Custom settings': 'Configuración personalizada', 'Save profile': 'Guardar perfil',
    'Current password': 'Contraseña actual', 'New password': 'Nueva contraseña', '14 characters minimum': 'Mínimo 14 caracteres', 'Changing your password ends all sessions and revokes all MCP tokens.': 'Al cambiar tu contraseña se cerrarán todas las sesiones y se revocarán todos los tokens de MCP.', 'Change password': 'Cambiar contraseña',
    'MCP endpoint': 'Endpoint de MCP', 'Token name': 'Nombre del token', 'Create token': 'Crear token', 'Copy this token now. It will not be shown again. Send it as Authorization: Bearer <token>.': 'Copia este token ahora. No volverá a mostrarse. Envíalo como Authorization: Bearer <token>.', 'New token': 'Nuevo token', 'Copied': 'Copiado', 'Copy token': 'Copiar token', 'Assigned boards': 'Tableros asignados', 'No boards selected': 'No hay tableros seleccionados', 'Clear boards': 'Quitar tableros', 'assigned': 'asignados', 'No board access': 'Sin acceso a tableros', 'Save boards': 'Guardar tableros', 'Revoke token': 'Revocar token',
    'Account management': 'Administración de cuentas', 'Disabled': 'Deshabilitada', 'Admin': 'Administrador', 'Manage account': 'Administrar cuenta', 'New account': 'Nueva cuenta', 'Initial password': 'Contraseña inicial', 'System administrator': 'Administrador del sistema', 'Boards this user can access': 'Tableros a los que puede acceder este usuario', 'Disabled account': 'Cuenta deshabilitada', 'Reset password': 'Restablecer contraseña', 'Leave blank to keep the current password': 'Déjalo vacío para mantener la contraseña actual', 'Save account': 'Guardar cuenta', 'Create account': 'Crear cuenta',
    'Bug': 'Error', 'Feature': 'Funcionalidad', 'Design': 'Diseño', 'Docs': 'Documentación', 'Refactor': 'Refactorización', 'Test': 'Prueba', 'Chore': 'Mantenimiento', 'Research': 'Investigación',
    'Language': 'Idioma', 'English': 'English', 'Português (Brasil)': 'Português (Brasil)', 'Español (México)': 'Español (México)', 'Choose language': 'Elegir idioma', 'Photo zoom': 'Zoom de la foto',
    'Backup': 'Respaldo', 'Connect a Dropbox app to store automatic database backups. Backups run 10 minutes after changes stop. If changes continue, a backup runs after 1 hour without a saved backup.': 'Conecta una aplicación de Dropbox para guardar copias de seguridad automáticas de la base de datos. Se realizan 10 minutos después de que cesen los cambios. Si continúan, se guarda un respaldo tras 1 hora sin guardar.', 'Dropbox app key': 'Clave de la aplicación de Dropbox', 'Dropbox access token': 'Token de acceso de Dropbox', 'Enter a new token to replace the saved token': 'Ingresa un token nuevo para reemplazar el guardado', 'Dropbox connected': 'Dropbox conectado', 'Dropbox not connected': 'Dropbox desconectado', 'Last backup': 'Último respaldo', 'Last backup error': 'Error del último respaldo', 'Disconnect': 'Desconectar', 'Back up now': 'Respaldar ahora', 'Save Dropbox settings': 'Guardar configuración de Dropbox', 'Connect Dropbox': 'Conectar Dropbox', 'Dropbox connected successfully.': 'Dropbox conectado correctamente.', 'Dropbox disconnected.': 'Dropbox desconectado.', 'Backup completed.': 'Respaldo completado.', 'Dropbox connection failed.': 'No se pudo conectar con Dropbox.', 'Dropbox disconnection failed.': 'No se pudo desconectar Dropbox.', 'Backup failed. Check the Dropbox connection and try again.': 'Falló el respaldo. Verifica la conexión con Dropbox e inténtalo de nuevo.',
};

export function LanguageProvider ( { children }: { children: ReactNode; } )
{
    const [ language, setLanguageState ] = useState<Language>( () =>
    {
        const saved = localStorage.getItem( 'soso-language' );
        return saved === 'pt-BR' || saved === 'es-MX' ? saved : 'en';
    } );
    useEffect( () => { document.documentElement.lang = language; }, [ language ] );
    function setLanguage ( next: Language )
    {
        localStorage.setItem( 'soso-language', next );
        setLanguageState( next );
        document.documentElement.lang = next;
    }
    const t = ( text: string ) => language === 'pt-BR' ? translations[ text ] ?? text : language === 'es-MX' ? spanishTranslations[ text ] ?? text : text;
    return <LanguageContext.Provider value={ { language, setLanguage, t } }>{ children }</LanguageContext.Provider>;
}
